name: Main Workflow

on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.11.0
          run_install: false
      - uses: actions/setup-node@4.4.0
        with:
          node-version: 23.10.0
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm lint
        continue-on-error: true

  test:
    name: Test
    runs-on: ubuntu-24.04
    needs:
      - lint

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.11.0
          run_install: false
      - uses: actions/setup-node@4.4.0
        with:
          node-version: 23.10.0
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
